package Airinda;

public class Day15Ngoding {
    public static void main(String[] args) {
     int x = 25;
     int y = 8;
     
     int penjumlahan = x + y ;
     int pengurangan = x - y ;
     
        System.out.println("nilai x = " + x);
        System.out.println("nilai y = " + y);
        System.out.println("penjumlahan (x + y)=" + penjumlahan);
        System.out.println("pengurangan (x - y)=" + pengurangan);        
        
   }
}
