public class day3 {
    public static void main(String[] args) {
    System.out.println("\t>> perkenala diri <<\nnama saya airinda\nsaya berasal dari mamuju tengah");
        System.out.println("\nada beberapa wish list cita cita saya yaitu:");
        String a = "dokter" ;
        String b = "engineer" ;
        String c = "dosen" ;
        String d = "polwan" ;
        
        System.out.println(a + "\n" +b + "\n"+ c + "\n" +d);
        
        System.out.println("\t  saya nemilih:");
        System.out.println(c);
          
                
        /*
        \n mendeklarasikan barisan baru atau enter
        \t mendeklarasikan spasi atau tab
        */
        
    }
     }
