public class day6 {

    public static void main(String[] args) {
        System.out.println("==BIODATA MAHASISWA BARU UNIVERSITAS SULAWESI BARAT==\n");
        String nama = "Airinda";
        String alamat = "Pangale";
        String alumni = "UPTD SMAN 1 PANGALE";
        String fakultas = "Teknik";
        String prodi = "Informatika";
        Float TB = 156.9f ;
        double BB = 46.4 ;
        
        System.out.println("nama :" + nama);     
        System.out.println("alamat :" + alamat);     
        System.out.println("alumni :" + alumni);     
        System.out.println("fakultas :" + fakultas);     
        System.out.println("prodi :" + prodi);     
        System.out.println("Tb :" + TB);     
        System.out.println("BB :" + BB); 
        
        /*
        Tipe data float memiliki ukuran 32 bit dan memiliki aturan yaitu setiap angka akhir nya di berikan tanda/simbol f
        Tipe data double memiliki ukuran 64 bit  
        */
    }
}
