package Airinda;

public class Day7Ngoding {
    public static void main(String[] args) {
        System.out.println("kerjalah soal latihan pilihan ganda berikut:");
        System.out.println("1.rata rata nilai 4 siswa 75.jika 3 siswa memperoleh nilai 70,80,dan 76,\nmaka nilai siswa keempat adalah");
        char a,b,c,d;
        a='a';
        b='b';
        c='c';
        d='d';
        
        int e=70;
        int f=72;
        int g=74;
        int h=75;
        
        System.out.println("a: "+ e);
        System.out.println("b: "+ f);
        System.out.println("c: "+ g);
        System.out.println("d: "+ h);
        boolean i,j;
        i = true;
        j = false;
        System.out.println("jawaban yang benar adalah "+ c+"." +" "+g +" "+ i);
        
        /*tipe data char untuk menyimpan 1 karakter saja seperti huruf,angka,atau simbol lainnya
        tipe data boolean untuk menyimpan nilai logika,hanya ada 2 yaitu true(benar) dan false(salah)
        */
     }
}
