package Airinda;
import java.util.Scanner;
public class Day81Ngoding {
    public static void main(String[] args) {
            Scanner airin = new Scanner(System.in); 
            System.out.println("LATIHAN AKSES ELEMEN ARRAY DENGAN INDEKS");
            int [] angka = {10,20,30,40,50};
            System.out.println("Elemen indeks 0: "+angka[0]);
            System.out.println("Elemen indeks 1: "+angka[1]);
            System.out.println("Elemen indeks 2: "+angka[2]);
            System.out.println("Elemen indeks 3: "+angka[3]);
            System.out.println("Elemen indeks 4: "+angka[4]);
            
    }
}
