package Airinda;

public class Day8Ngoding {
    public static void main(String[] args) {
        System.out.println("==BIO0DATA MAHASISWA BARU==");
        String A ="Airinda adalah Mahasiswa Baru Universitas Sulawesi Barat";
        String B ="Fakultas Teknik Program Studi Informatika";
        String C ="ia berasal dari Pangale Kabupaten Mamuju Tengah";
        String D ="Lahir di Mamuju pada 29 Januari 2008";
        String E ="Anak ke-2 dari 3 Bersaudara";
        String F ="Anak dari Pasangan Bapak Darwis a dan Ibu Hastuti ";
                
        System.out.println(A);
        System.out.println(B);
        System.out.println(C);
        System.out.println(D);
        System.out.println(E);
        System.out.println(F);
        
        //tipe data string di pakai untuk menyimpan kumpulan karakter atau teks
                
    }
}
