package Airinda;

public class Day9Ngoding {
    public static void main(String[] args) {
        System.out.println("==DEKLARASI");
        byte umur ;
        short Lb;
        long tinggi;
        float ipk;
        double berat;
        char jk;
        int gaji;
        boolean status;
        
        System.out.println("==INISIALISASI==");
        umur = 16;
        Lb = 67;
        tinggi = 156;
        ipk = 4f;
        berat = 46;
        jk = 'p';
        gaji = 4;
        status = true;
        
        System.out.println("==SEBELUM UPDATE==");
        System.out.println("umur: "+ umur);
        System.out.println("Lb: "+ Lb);
        System.out.println("tinggi: "+ tinggi);
        System.out.println("ipk: "+ ipk);
        System.out.println("berat: "+ berat);
        System.out.println("jk: "+ jk);
        System.out.println("gaji: "+ gaji);
        System.out.println("status: "+ status);
        
        System.out.println("==SETELAH UPDATE==");
        umur = 17;
        Lb = 68;
        tinggi = 157;
        ipk = 5;
        berat = 47;
        jk = 'L';
        gaji = 5;
        status = false;
        
        System.out.println("umur: " + umur);
        System.out.println("Lb: " + Lb);
        System.out.println("tinggi: " + tinggi);
        System.out.println("ipk: " + ipk);
        System.out.println("berat: " + berat);
        System.out.println("jk: " + jk);
        System.out.println("gaji: " + gaji);
        System.out.println("status: " + status);
                
        
    }
    
}
